#Pull Base Image
FROM tomcat:8.0

#Maintainer
MAINTAINER "Sai"

WORKDIR /usr/local/tomcat/webapps/
RUN mkdir MyApp
#WORKDIR /usr/local/tomcat/webapps/MyApp
copy ./index.html /usr/local/tomcat/webapps/MyApp
WORKDIR /usr/local/tomcat/webapps/MyApp



$ docker build -t <imagename> <path>
$ docker run -d -- name <container name> -p exposed port:internal port <image name>:tag
$ docker exec -it <container name> /bin/bash
